#!/bin/bash
# run.sh
# Generate a Gromacs distance restraint file (distres.itp) and wire it into
# topology.top
#
# Prerequisite: gmx.gro / gmx.top already generated by amb2gro or centering_gro
#
# Output:
#   distres.itp  - restraint definitions including [ intermolecular_interactions ]
#   gmx.top      - an #include of distres.itp is appended at the end
#
# NOTE:
#   - Distances are in nm (0.26 nm = 2.6 A)
#   - Set them in the order up2 > up1 > lo
#   - Each pair must name exactly one atom via the MDtraj atom selection language
#     e.g. "resname MGX and name O2 and resid 200"
#   - [ intermolecular_interactions ] applies only between different molecule
#     groups (intramolecular restraints belong in [ bonds ])
#
# Example:
#   bash run.sh

set -e

GRO="gmx.gro"
TOP="gmx.top"

# -----------------------------------------------------------------------
# Basic case: distance restraints between a metal ion (MGX) and active-site
# residues, to maintain the protein-metal coordination
# -----------------------------------------------------------------------

# Keeping the restrained pairs in arrays makes this easier to read
# Each pair: (lo, up1, up2, sel1, sel2)
# lo=0.0 means no lower bound (distances are non-negative, so 0.0 is fine)

# MDtraj atom selection strings assigned to sel1 and sel2
# Several pairs can be given, separated by commas
MGX_O1="resname MGX and name O1"
MGX_O2="resname MGX and name O2"
GLY_N="resname GLY and name N and resid 10"
GLY_N2="resname GLY and name N and resid 20"
HID_AND1="resname HID and name AND1"
HID_N="resname HID and name N"
GLH_OE1="resname GLH and name OE1"
GLH_OE2="resname GLH and name OE2"

mdtbx gen_distres \
    -g ${GRO} \
    -p ${TOP} \
    -lo 0.0 \
    -up1 0.26 0.26 0.28 0.30 0.30 \
    -up2 0.28 0.28 0.30 0.32 0.32 \
    -o distres \
    -s1 "${MGX_O2},${MGX_O2}, ${MGX_O1}, ${MGX_O2},${GLY_N2}" \
    -s2 "${GLY_N}, ${HID_AND1},${GLH_OE2},${HID_N}, ${GLH_OE1}"

echo "distres.itp generated and appended to ${TOP}"

# -----------------------------------------------------------------------
# How to activate this from the mdp file
# Add the following to the mdp file to enable the restraints:
#   define = -DDISTRES -DDISTRES_FC=1000
# DISTRES_FC is the force constant (kJ/mol/nm^2)
# -----------------------------------------------------------------------

# -----------------------------------------------------------------------
# Uniform-bound case: apply the same bounds to every pair
# Passing a single value to -lo, -up1, -up2 applies it to all pairs
# -----------------------------------------------------------------------
# mdtbx gen_distres \
#     -g ${GRO} \
#     -p ${TOP} \
#     -lo 0.0 \
#     -up1 0.28 \
#     -up2 0.30 \
#     -o distres_uniform \
#     -s1 "${MGX_O2},${MGX_O2}" \
#     -s2 "${GLY_N}, ${HID_AND1}"

echo "All done."
