from pathlib import Path

import numpy as np
from pymol import cmd

from .arrow import cgo_arrow

REQUIRED_KEYS = (
    "components",
    "explained_variance",
    "mean_xyz",
    "atom_names",
    "residue_ids",
    "residue_names",
)


def _load_pca_npz(npz_path: str):
    npz = np.load(npz_path, allow_pickle=False)
    missing_keys = [key for key in REQUIRED_KEYS if key not in npz]
    if missing_keys:
        missing = ", ".join(missing_keys)
        raise ValueError(f"Missing keys in PCA metadata: {missing}")
    return npz


def _normalize_atom_name(atom_name: str) -> str | None:
    if atom_name is None:
        return None
    atom_name = atom_name.strip()
    if atom_name == "" or atom_name.lower() == "all":
        return None
    return atom_name


def show_pca_mode_from_npz(
    npz_path: str,
    pc: str = "1",
    scale: str = "5.0",
    stride: str = "5",
    atom_name: str = "CA",
    radius: str = "0.10",
    color: str = "cyan red",
    name_prefix: str = "pca_mode",
):
    """
    Draw PCA mode vectors stored in an .npz file generated by `mdtbx pca -oz`.

    Example
        show_pca_mode_from_npz cvs/pca_backbone.npz, 1, 5.0, 5, CA, 0.10, cyan red
    """

    npz_file = Path(npz_path).expanduser()
    if not npz_file.exists():
        raise FileNotFoundError(f"PCA metadata file not found: {npz_file}")

    pc_index = int(pc)
    scale_value = float(scale)
    stride_value = max(1, int(stride))
    radius_value = float(radius)
    atom_name_value = _normalize_atom_name(atom_name)

    data = _load_pca_npz(str(npz_file))
    components = data["components"]
    explained_variance = data["explained_variance"]
    mean_xyz = data["mean_xyz"]
    atom_names = data["atom_names"].astype(str)
    residue_ids = data["residue_ids"]
    residue_names = data["residue_names"].astype(str)
    unit_scale = (
        float(data["unit_scale_to_angstrom"])
        if "unit_scale_to_angstrom" in data
        else 10.0
    )
    explained_variance_ratio = (
        data["explained_variance_ratio"]
        if "explained_variance_ratio" in data
        else np.zeros_like(explained_variance)
    )

    if pc_index < 1 or pc_index > components.shape[0]:
        raise ValueError(f"pc must be between 1 and {components.shape[0]}")

    mode_vectors = (
        components[pc_index - 1]
        * np.sqrt(explained_variance[pc_index - 1])
        * scale_value
    )

    selected_indices = np.arange(mean_xyz.shape[0])
    if atom_name_value is not None:
        selected_indices = selected_indices[atom_names == atom_name_value]
    selected_indices = selected_indices[::stride_value]

    if selected_indices.size == 0:
        raise ValueError("No atoms selected for visualization")

    group_name = cmd.get_unused_name(f"{name_prefix}_pc{pc_index}")
    for display_index, atom_index in enumerate(selected_indices, start=1):
        start = (mean_xyz[atom_index] * unit_scale).tolist()
        end = ((mean_xyz[atom_index] + mode_vectors[atom_index]) * unit_scale).tolist()
        arrow_name = f"{group_name}_{display_index}"
        cgo_arrow(start, end, radius=radius_value, color=color, name=arrow_name)
        cmd.group(group_name, arrow_name)

    explained_ratio = float(explained_variance_ratio[pc_index - 1]) * 100.0
    atom_filter = atom_name_value if atom_name_value is not None else "all atoms"
    first_atom_index = selected_indices[0]
    print(
        "show_pca_mode_from_npz: "
        f"group={group_name}, pc={pc_index}, arrows={selected_indices.size}, "
        f"atom_filter={atom_filter}, first_atom={residue_names[first_atom_index]}"
        f"{residue_ids[first_atom_index]}:{atom_names[first_atom_index]}, "
        f"variance={explained_ratio:.2f}%"
    )


cmd.extend("show_pca_mode_from_npz", show_pca_mode_from_npz)
