#!/bin/bash
# run.sh
# Estimate crystallographic or conserved water sites with 3D-RISM.
#
# Prerequisite: parm7/rst7 files generated by leap (build_solution)
#
# Usage:
#   bash run.sh

set -e

PRMTOP="leap.parm7"
COORD="leap.rst7"
OUTPUT="placed_water.pdb"

# -----------------------------------------------------------------------
# Basic case: generate an xvv with 1D-RISM, then run 3D-RISM.
# -----------------------------------------------------------------------
mdtbx place_solvent \
    -p ${PRMTOP} \
    -x ${COORD} \
    -o ${OUTPUT} \
    --solvent-model cSPCE \
    --xvv-output cSPCE_300.xvv \
    --temperature 300.0 \
    --closure kh \
    --grdspc 0.5 \
    --buffer 14.0 \
    --solvcut 14.0 \
    --threshold 1.5 \
    --exclusion-radius 2.6

echo "Basic run done -> ${OUTPUT}"

# -----------------------------------------------------------------------
# Reuse an xvv for multiple structures with the same solvent and temperature.
# Saving the result avoids repeating the 1D-RISM calculation.
# -----------------------------------------------------------------------
# Example: save the generated xvv on the first run.
# mdtbx place_solvent \
#     -p ${PRMTOP} -x ${COORD} \
#     --solvent-model cSPCE --temperature 300.0 \
#     --xvv-output cSPCE_300.xvv

XVV="cSPCE_300.xvv"
if [ -f "${XVV}" ]; then
    mdtbx place_solvent \
        -p ${PRMTOP} \
        -x ${COORD} \
        -o placed_water_reuse.pdb \
        --xvv ${XVV} \
        --temperature 300.0 \
        --closure kh \
        --threshold 1.5 \
        --exclusion-radius 2.6
    echo "xvv reuse run done -> placed_water_reuse.pdb"
fi

# -----------------------------------------------------------------------
# Place only the top N sites, for example around a protein active site.
# -----------------------------------------------------------------------
mdtbx place_solvent \
    -p ${PRMTOP} \
    -x ${COORD} \
    -o placed_water_top20.pdb \
    --solvent-model cSPCE \
    --temperature 300.0 \
    --closure kh \
    --threshold 1.5 \
    --exclusion-radius 2.6 \
    --max-sites 20

echo "Top-20 sites run done -> placed_water_top20.pdb"

# -----------------------------------------------------------------------
# Higher-resolution case with a finer grid and weaker density threshold.
# Compute cost scales approximately with the inverse cube of grdspc.
# -----------------------------------------------------------------------
mdtbx place_solvent \
    -p ${PRMTOP} \
    -x ${COORD} \
    -o placed_water_hires.pdb \
    --solvent-model cSPCE \
    --temperature 300.0 \
    --closure kh \
    --grdspc 0.3 \
    --buffer 14.0 \
    --solvcut 14.0 \
    --tolerance 1e-6 \
    --threshold 1.0 \
    --exclusion-radius 2.6

echo "High-resolution run done -> placed_water_hires.pdb"

echo "All done."
